---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.17.6
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    deploymentStrategy:
      type: Recreate
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
    adminPassword: "${SECRET_GRAFANA_PASSWORD}"
    grafana.ini:
      server:
        root_url: "https://grafana.${SECRET_DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth:
        signout_redirect_url: https://id.${SECRET_DOMAIN}/application/o/grafana/end-session/
        # Optionally enable auto-login
        oauth_auto_login: true
      auth.basic:
        disable_login_form: true
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        name: Authentik
        client_id: grafana
        client_secret: ${SECRET_AUTHENTIK_GRAFANA_CLIENT_SECRET}
        scopes: openid profile email
        auth_url: https://id.${SECRET_DOMAIN}/application/o/authorize/
        token_url: https://id.${SECRET_DOMAIN}/application/o/token/
        api_url: https://id.${SECRET_DOMAIN}/application/o/userinfo/
      auth.generic_oauth.group_mapping:
        role_attribute_path: "contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
        org_id: 1
      auth.anonymous:
        enabled: true
        org_id: 1
        org_role: Viewer
      security:
        allow_embedding: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: "traefik"
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        # external-dns/is-public: "true"
        # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
      - "grafana.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "grafana.${SECRET_DOMAIN}"
        secretName: grafana-cert
    persistence:
      enabled: true
      existingClaim: grafana-pvc
    podAnnotations:
      configmap.reloader.stakater.com/reload: "grafana"