---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age10qumk0cqhe2zqeh0swzhr8hpyd0m3d8xtgv7lt5p2th763l743fsmfq8w3
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age10qumk0cqhe2zqeh0swzhr8hpyd0m3d8xtgv7lt5p2th763l743fsmfq8w3
