---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgresql
  namespace: security
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi