apiVersion: v1
kind: Secret
metadata:
    name: ask-mr-robot
    namespace: default
    labels:
        app.kubernetes.io/name: ask-mr-robot
        app.kubernetes.io/instance: ask-mr-robot
type: Opaque
stringData:
    settings.json: ENC[AES256_GCM,data:TSATsqk82zQjj7J9J2C7wnfnZ5ygV0DrcMpNUdxjCTeigjuzkcFwdpnYtWYPdmkUwEDZ+0szzlrt8Ra256m68Miqrfn3Z8iGPbOg1GdnUyTzsR+E8YsOgoMBgTrkasHwUrFL3OJnnZGGYlPoMMrL7j6zLN5MfkVHVuSGu8t+/cUTt7T7G1MiFi6GAs2p9oFxy2c/493XIA2ZmcoppIljKownvcaSSGRXy5kqYgUo695suuzmtNBEsdfCj3/wxt2RxEz+VrD3S5A+HJ99OaLOAUCzo+zwJVolOfbfOiRRun0JTVmaAKxWC8e9FQ4+5gSbGohXa+tRRA6uKsWXaqf9NHQD+Q63IBbsLgBwLaK97XOl2FXjaZz67edP4d59pjDWv0rDwZPDjbba,iv:6efmT6ATITZGHxe2OWIJxGCzsigHH6Nlkv5e0w7zvkQ=,tag:oYARZN6zmjNM3IpYoe4wbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10qumk0cqhe2zqeh0swzhr8hpyd0m3d8xtgv7lt5p2th763l743fsmfq8w3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQS93NXRTTUZWU256aTlF
            bFdldFJhQ09ZWEVNcklQWXNXUVFRSG9PSVhvCnVqYi9US3pYNk1JM3krQ3VZT2dk
            Si9rc3hyY0dEcTUzU0R0bzhQdGk3SkEKLS0tIHRtT0VrUVdMWDl1M1FBR2xjMTlZ
            WmRtVnZKY05LcFhjaU1lN0M1WnA1KzQK8TbmYenqBpUtPL0tOtOVRIP3gjze+VHZ
            Y4csYqyRETOVw2QwUeP41IORUqj3YZTxi6EnBVePjRFCT9oxygB6Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-20T14:12:23Z"
    mac: ENC[AES256_GCM,data:dDNKOljdVwoNfugwoXgJs63KR9qukofWMsctR6y23iHI/FNicw6MsIRiAGJB3ghCc3jjWJLcg0oOBCjk3X0/mcBItqxaWxMWoVpOcnopxaqSeNvQcyyDsYWYGMp1MEtm4LXFP2FUXDZCw56jplE4g5cQl+FFtxkPo5upk9lsfqE=,iv:wBSgkE32A7S1Goo/QilhfQZge39CrYTQrChv7CIhNno=,tag:hPOZQL7AII3IxTDt1DVGIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
