---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: keycloak
      version: 9.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/keycloak

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        kubernetes.io/tls-acme: "true"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hostname: auth.${SECRET_DOMAIN}
      paths:
        - path: /
      tls:
        enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
        scrapeTimeout: 30s
    extraEnvVars: 
      - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KC_HOSTNAME
        value: "auth.${SECRET_DOMAIN}"
