apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: dev
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://helm.goharbor.io
      # renovate: registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: harbor-charts
        namespace: flux-system
  values:
    expose:
      tls:
        # The ingress controller has a default certificate so we don't need to configure it
        certSource: none
      ingress:
        className: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          core: harbor.${SECRET_DOMAIN}
        tls:
        - hosts:
            - "harbor.${SECRET_DOMAIN}"
          secretName: "harbor-tls"
    externalURL: https://harbor.${SECRET_DOMAIN}

    trivy:
      enabled: false
    chartmuseum:
      enabled: false
    notary:
      enabled: false
