apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: dev
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://helm.goharbor.io
      # renovate: registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.9.6
      sourceRef:
        kind: HelmRepository
        name: harbor-charts
        namespace: flux-system
  values:
    expose:
      type: ingress
      tls:
        certSource: auto
        secret:
          secretName: "harbor-tls"
          notarySecretName: "harbor-notary-tls"
      ingress:
        className: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          core: harbor.${SECRET_DOMAIN}
          notary: harbor-notary.${SECRET_DOMAIN}
    externalURL: https://harbor.${SECRET_DOMAIN}

    trivy:
      enabled: false
    chartmuseum:
      enabled: false
    notary:
      enabled: false
