apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system
  - default
  - dev
  - flux-system
  - kube-system
  - monitoring
  - networking
  - security
  - system-upgrade
  - velero