apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - dev.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - networking.yaml
  - security.yaml
  - velero.yaml